[versions]
androidGradlePlugin = "8.10.0"
androidxActivity = "1.10.1"
androidxCore = "1.16.0"
androidJunit5Plugin = "1.12.0.0"
androidxCoreTesting = "2.2.0"
androidxLifecycle = "2.9.0"
androidxTest = "1.6.2"
androidxTestEspresso = "3.6.1"
androidxTestExt = "1.2.1"
conventionPlugin = "2.0.0-alpha.3"
dependencyAnalysis = "2.17.0"
googleMaterial = "1.12.0"
gradleVersions = "0.51.0"
kgpAndroidxComposeBom = "2024.02.00"
kgpAndroidxComposeCompiler = "1.5.14"
kgpAndroidxHiltCompiler = "1.2.0"
kgpCompileSdk = "35"
kgpDagger = "2.56.1"
kgpDokka = "2.0.0"
kgpJdk = "17"
kgpJunit4 = "4.13.2"
kgpJunitBom = "5.12.2"
kgpKotlinxSerialization = "1.4.1"
kgpMinSdk = "24"
kgpTargetSdk = "35"
kotlin = "2.1.20"
kotlinter = "5.0.2"
kotlinxCoroutines = "1.10.2"
kover = "0.9.1"
ksp = "2.1.20-1.0.32"
mavenPublish = "0.31.0"
mockk = "1.14.2"
truth = "1.4.4"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidxCoreTesting" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material-iconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-testJunit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-testManifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspresso" }
androidx-test-ext = { module = "androidx.test.ext:junit-ktx", version.ref = "androidxTestExt" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTest" }
gradlePlugins-kotlinter = { module = "org.jmailen.gradle:kotlinter-gradle", version.ref = "kotlinter" }
googleMaterial = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "kgpDagger" }
junit5-bom = { module = "org.junit:junit-bom", version.ref = "kgpJunitBom" }
jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "androidJunit5Plugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-lint = { id = "com.android.lint", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
conventions-root = { id = "com.kroger.gradle.root", version.ref = "conventionPlugin" }
conventions-androidApplication = { id = "com.kroger.gradle.android-application-conventions", version.ref = "conventionPlugin" }
conventions-androidLibrary = { id = "com.kroger.gradle.android-library-conventions", version.ref = "conventionPlugin" }
conventions-dependencyManagement = { id = "com.kroger.gradle.dependency-conventions", version.ref = "conventionPlugin" }
conventions-publishedAndroidLibrary = { id = "com.kroger.gradle.published-android-library-conventions", version.ref = "conventionPlugin" }
conventions-publishedKotlinLibrary = { id = "com.kroger.gradle.published-kotlin-library-conventions", version.ref = "conventionPlugin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "kgpDagger" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
dokka = { id = "org.jetbrains.dokka", version.ref = "kgpDokka" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersions" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
